### ISSUE TITLE
commonResp.Fee is float64

### ISSUE THREAD

**Issue by foundVanting** [sliveryou/submail-go-sdk#1]
internationalsms resp  
`{"status":"success","send_id":"2121eb96f4d740b15bcd7e8c0fccabf9","fee":0.08}`
but  fee is int
```
type commonResp struct {
	Status                  string `json:"status"`
	Code                    int    `json:"code"`
	Msg                     string `json:"msg"`
	SendId                  string `json:"send_id"`
	Fee                     int    `json:"fee"`
	SmsCredits              string `json:"sms_credits"`
	TransactionalSmsCredits string `json:"transactional_sms_credits"`
}
```

err: json: cannot unmarshal number 0.08 into Go struct field commonResp.fee of type int

**Comment by sliveryou** [comment]
fix in [25746cb](https://github.com/sliveryou/submail-go-sdk/commit/25746cb90b985e167b7bfb72cb053610b5e467d0#diff-611870eba70b306ec01db0964063e5af04add503c2194c59051f9ecdddc0c9ba)
